name: Build espeak-ng Android libs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Android NDK
        id: setup-ndk
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26c

      - name: ndk-build
        working-directory: android
        run: ${{ steps.setup-ndk.outputs.ndk-path }}/ndk-build

      - name: Upload .so files
        uses: actions/upload-artifact@v4
        with:
          name: espeak-ng-libs
          path: android/libs
